### ISSUE TITLE
Flake Updates & Github Rate Limit

### ISSUE THREAD

**Issue by psionic-k** [cargo2nix/cargo2nix#216]
People claim there's a way to configure git to do authenticated requests in actions.  I want to make an explicit issue for this in case others may run into the same thing.

**Comment by psionic-k** [comment]
cachix v15 install hunk:

```yaml
    - uses: cachix/install-nix-action@v15
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
```

https://github.com/cachix/install-nix-action    No longer needs manual enabling nix flakes either
