### ISSUE TITLE
using `rustToolchain` variable for creating workspace

### ISSUE THREAD

**Issue by JohnCarterGonzalez** [cargo2nix/cargo2nix#345]
In the example docs for hello-world the rust workspace is built using:
```nix
# the flake.nix file is spliced here for brevity...
# create the workspace & dependencies package set
rustPkgs = pkgs.rustBuilder.makePackageSet {
  rustVersion = "1.75.0";
  packageFun = import ./Cargo.nix;
};
# rest of flake...
```

I usually create my development environments through a single rustToolchain file like so:
```nix
# again the flake is spliced for brevity...
# 👇 note that it refers to the path ./rust-toolchain.toml
rustToolchain = pkgs.pkgsBuildHost.rust-bin.fromRustupToolchainFile ./rust-toolchain.toml;
in
with pkgs;
{
  devShells.default = mkShell {
    buildInputs = [
     rustToolchain
    ];
};
# rest of flake.nix....
```
Not saying this is the best approach, I am just curious if something like this is possible in the build dev-env section for cargo2nix? Thanks for your time.

**Comment by JohnCarterGonzalez** [comment]
an example of what I mean would be like:
```nix
rustToolchain = pkgs.pkgsBuildHost.rust-bin.fromRustupToolchainFile ./rust-toolchain.toml;
rustPkgs = pkgs.rustBuilder.makePackageSet {
  rustupToolchain = rustupToolchain # not sure what the declaring variable would be here
  packageFun = import ./Cargo.nix;
  # ...
 ```
 
 and the rust-toolchain.toml would look like:
 ```toml
 [toolchain]
channel = "1.75"
profile = "minimal"
components = [ "rustfmt", "clippy" ]
targets = [ "x86_64-apple-darwin", "aarch64-apple-darwin", "wasm32-wasi" ]
```
the dev-env would be built using the toml file and the cargo2nix would build the `bin` rust pkg. I hope the example makes sense!
