### ISSUE TITLE
bug: unable to determine which branch's rev that git depends on

### ISSUE THREAD

**Issue by jetjinser** [cargo2nix/cargo2nix#369]
If `rev` is not in the `HEAD` positioned branch, `builtins.fetchGit` cannot find it.

### To reproduce
minimal case: https://github.com/jetjinser/madsim-br

the point is:
```toml
[dependencies]
tokio-stream = { git = "https://github.com/madsim-rs/tokio.git", rev = "fe39bb8e" }
```
the https://github.com/madsim-rs/tokio/commit/fe39bb8e in branch `madsim`.

```bash
nix build
```
gets error like:
```
error: Cannot find Git revision 'fe39bb8e8ab0ed96ee1b4477ab5508c20ce017fb' in ref 'HEAD' of repository 'https://github.com/madsim-rs/tokio.git'! Please make sure that the rev exists on the ref you've specified or add allRefs = true; to fetchGit.
```
